  name: Add To GitHub projects
  uses: actions/add-to-project@v0.3.0
  with:
    # URL of the project to add issues to
    project-url: https://github.com/users/eluqueMeli/projects/1/views/1
    # A GitHub personal access token with write access to the project
    github-token: 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
    # A comma-separated list of labels to use as a filter for issue to be added
    labeled: # optional
    # The behavior of the labels filter, AND to match all labels, OR to match any label, NOT to exclude any listed label (default is OR)
    label-operator: # optional
